package backend.utils

sealed trait Enums extends Enumeration {
  def isValid(s: String): Boolean = values.exists(_.toString.toLowerCase == s.toLowerCase)
}

object Languages extends Enums {
  val Albanian, English = Value
}

object Keywords extends Enums {
  val NearBeach,
  Downtown,
  FamilyFriendly,
  MountainsSurrounding,
  Cozy,
  Spacious,
  Quite,
  Modern,
  PetFriendly = Value
}

object FilterKeywords extends Enums {
  val Family_Vacation,
    Going_away_with_Friends,
    Spontaneous_trip,
    Looking_for_a_cosy_place,
    Business_trip = Value
}

object keywordMapper {
  import FilterKeywords._
  import Keywords._

  val mappedKeywords: Map[FilterKeywords.Value, Set[Keywords.Value]] = Map(
    Family_Vacation -> Set(Downtown, FamilyFriendly, MountainsSurrounding, Cozy, Quite, PetFriendly, NearBeach),
    Going_away_with_Friends -> Set(Downtown, FamilyFriendly, Modern, Spacious, MountainsSurrounding, NearBeach),
    Spontaneous_trip -> Keywords.values,
    Looking_for_a_cosy_place -> Set(FamilyFriendly, MountainsSurrounding, Quite, PetFriendly),
    Business_trip -> Keywords.values,
  )
}

object Roles extends Enums {
  val SuperAdmin, PropertyOwner, PropertyManager = Value
}

object Permissions extends Enums {
  val ReadAllUsersData, ReadProperties, UpdateProperties, DeleteProperties, InsertProperties, ReadUsers, UpdateUsers,
      DeleteUsers, InsertUsers, ReadBedTypes, InsertBedTypes, UpdateBedTypes, DeleteBedTypes,
      ReadCompanies, UpdateCompanies, DeleteCompanies, InsertCompanies, InsertRooms, UpdateRooms,
      ReadRooms, DeleteRooms, InsertImages, DeleteImages, DownloadImages =
    Value
}

object RolesAndPermissions {
  import Permissions._
  import Roles._

  val rolePermissions = Map(
    SuperAdmin -> Set(ReadAllUsersData,InsertCompanies,DeleteCompanies,UpdateCompanies,ReadCompanies),
    PropertyOwner -> Set(
      ReadProperties,
      UpdateProperties,
      DeleteProperties,
      InsertProperties,
      ReadUsers,
      UpdateUsers,
      DeleteUsers,
      InsertUsers,
      ReadBedTypes,
      InsertBedTypes,
      UpdateBedTypes,
      DeleteBedTypes,
      InsertImages,
      DeleteImages,
      DownloadImages,
      InsertRooms,
      UpdateRooms,
      ReadRooms,
      DeleteRooms,
      DeleteCompanies
    ),
    PropertyManager -> Set(
      ReadProperties,
      UpdateProperties,
      ReadUsers,
      UpdateUsers,
      InsertRooms,
      ReadRooms,
      UpdateRooms,
      DeleteRooms,
      ReadBedTypes,
      InsertImages,
      DeleteImages,
      DownloadImages
    )
  )
}

object PropertyPermissions extends Enums {
  val Read, Write = Value
}

object PropertyTypes extends Enums {
  val Hotel, Apartment, HomeVilla, Other = Value
}

object PaymentMethodTypes extends Enums {
  val DebitCreditCard, Cash, BankTransfer, Paypal, Paysera, Other = Value
}

object Countries extends Enums{
  val Kosove, Albania, Montenegro = Value
}

//object Cities extends  Enums {
//  val Deçan,Dragash,Ferizaj,Fushë_Kosovë,Gjakovë,Gjilan,Gllogoc,Graçanicë,Hani_i_Elezit,
//  Istog,Junik,Kamenicë,Kaçanik,Klinë,Kllokot,Leposaviq,Lipjan,Malishevë,Mamushë,Mitrovicë,Novobërdë,
//  Obiliq,Partesh,Pejë,Podujevë,Prishtinë,Prizren,Rahovec,Ranillug,Shtime,Shtërpcë,Skënderaj,Suharekë,
//  Viti,Vushtrri,Zubin_Potok,Zveçan = Value
//}

object Villages extends Enums {
  val Babiq,Baran,Bellopaq,Bllagajë,Bogë,Brestovik,Brezhanik,Broliq,Buçan,Çallapek,Dobërdol,
  Drelaj,Duboçak,Dubovë,Dugaivë,Gllaviçicë,Gorazhdec,Graboc,Jabllanicë_e_Madhe,
  Jabllanicë_e_Vogël,Katundi_i_Ri,Kërstoc,Kliqinë,Koshutan,Kosuriq,Kotradiq,Kryshec,Kuçishtë,Leshan,Lëvoshë,
  Lipë,Loxhë,Lubeniq,Llaz_Bellopaq,Llozhan,Malaj,Millovanc,Nabërgjan,Nakëll,Nepolë,
  Novosellë,Osojë,Ozdrim,Pavlan,Pejë,Pepiq,Pishtan,Poçestë,Qyshk,Radavc,Ramun,Rashiq,Raushiq,Rekë_e_Allagës,Rosulë,
  Ruhot,Sigë,Stankaj,Sverkë,Shkrel,Shtupeq_i_Madh,Shtupeq_i_Vogël,Treboviq,Trestenik,Turjakë,Vitomiricë,Vragoc,
  Vranoc,Zagërmë,Zahaq,Zllapek,Banjicë,Belicë,Cerkolez,Cerrcë,Dobrushë,Dragolec,
  Drejë,Dubovë_e_Vogël,Gjurakoc,Istog,Istog_i_Poshtëm,Kaliqan,Kashicë,Kërninë,Kosh,Kovragë,Lubovë,
  Lubozhdë,Llugë,Llukac_i_Begut,Llukac_i_Thatë,Mojstir,Muzhevinë,Orobërdë,Osojan,Polanë,Prekallë,Prigodë,
  Rakosh,Serbobran,Sinajë,Staradran,Studenicë,Suhogërllë,Shalinovicë,Shushicë,Tomoc,Trubuhoc,Tuçep,Uçë,Veriq,
  Veriq_i_Ri,Vrellë,Zabllaq,Zallq,Zhakovë,
  Baballoq,Beleg,Belle,Carrabreg_i_Epërm,Carrabreg_i_Ulët,
  Dashinoc,Deçan,Drenoc,Dubovik,Gllogjan,Gramaçel,Hulaj,Irzniq,Isniq,Lëbushë,
  Lumbardh,Lloqan,Llukë_e_Epërme,Llukë_e_Ulët,Maznik,Dubravë,Papiq,Pobërxhë,Pozhar,Prapaqan,Prekolluk,Prilep,
  Rastavicë,Ratish_i_Epërm,Ratish_i_Ulët,Sllup,Strellc_i_Epërm,Strellc_i_Ulët,Shaptej,Voksh,Vranoc_i_Vogël,
  Baçkë,Bellobradë,Blaç,Brezne,Brod,Brodosanë,Brrut,Buçë,Buzez,Dikancë,Dragash,Glloboçicë,Kapre,Kërstec,Kosavë,
  Krushevë,Kuk,Kukjan,Kuklibeg,Leshtan,Lubovishtë,Mlikë,Orqushë,Plavë,Pllajnik,Radesh,Rapqë,Restelicë,Rrenc,
  Shajnë,Vranishtë,Xërxë,Zaplluzhë,Zgatar,Zlipotok,Zym,
  Bablak,Babush_i_Sërbëve,Balaj,Bibaj,Burrnik,Cërnillë,
  Doganaj,Dramjak,Ferizaj,Fshat_i_Vjetër,Gaçkë,Gërlicë,Greme,Jezerc,Komogllavë,Kosinë,
  Lloshkobare,Manastircë,Mirash,Mirosalë,Muhoc,Nekodim,Nerodime_e_Epërme,Nerodime_e_Poshtme,Papaz,
  Pleshinë,Pojatë,Prelez_i_Jerlive,Prelez_i_Muhaxherve,Rahovicë,Rakaj,Sazlië,Slivovë,Softaj,Sojevë,Surqinë,
  Talinoc_i_Jerlive,Talinoc_i_Muhaxherëve,Tankosiq,Tërn,Varosh,Zaskok,Zllatar,
  Bardh_i_Madh,Bardh_i_Vogël, Bresje,Fushë_Kosovë,Graboc_i_Poshtëm,Harilaç,Henc,Kuzmin,Lismir,Miradi_e_Epërme,Miradi_e_Poshtme,Nakaradë,
  Pomazotin,Sllatinë_e_Madhe,Sllatinë_e_Vogël,Vragoli,
  Babaj_i_Bokës,Bardhaniq,Bardhasan,Batushë,Bec,Berjah,
  Bishtazhin,Bitesh,Brekoc,Brovinë,Cërmjan,Dallashaj,Damjan,Devë,Doblibarë,Dobrixhë,
  Dobrosh,Dol,Dujakë,Duzhnjë,Firajë,Firzë,Fshaj,Gërçinë,Gërgoc,Goden,Guskë,Gjakovë,Hereç,
  Jabllanicë,Jahoc,Janosh,Korenicë,Kralan,Kusar,Kushavec,Lipovec,Lugbunar,
  Llugaxhi,Madanaj,Marmull,Mejë,Meqe,Moglicë,Molliq,Morinë,Nec,Nivokaz,Novosellë_e_Epërme,
  Novosellë_e_Ulët,Orize,Osek_Hylë,Osek_Pashë,Pacaj,Palabardhë,Pjetërshan,Plançor,Ponoshec,
  Popoc,Qerim,Qerret,Raçë,Radoniq,Rakoc,Rakovinë,Ramoc,Rashkoc,Rogovë,Rracaj,Rrezinë,Rrypaj,
  Skivjan,Smaq,Smolicë,Sopot,Stubëll,Sheremet,Shishman,Trakaniq,Ujz,Vogovë,Vraniq,Zylfaj,Zhabel,
  Zhdredhë,Zhub,
  Bilincë,Bresalc,Bukovik,Burincë,Capar,Cërnicë,Çelik,Demiraj,Dobërçan,Dunav,Gadish,Gumnishtë,Gjilan,Haxhaj,Inatoc,Kishnapolë,Kmetoc,Kravaricë,Kurexh,Lipovicë,
  Livoç_i_Epërm,Livoç_i_Ulët,Lladovë,Llashticë,Llovcë,Malishevë,Muçibabë,Nasalë,
  Përlepnicë,Pidiq,Pograxhë,Ponesh,Selishtë,Sllakoc_i_Epërm,Sllakoc_i_Ulët,
  Sllubicë,Stançiq,Stublinë,Shillovë,Shurdhan,Terzijaj,Uglar,Velekincë,
  Vërbicë_e_Kmetocit,Vërbicë_e_Zhegocit,Vrapçiq,Zhegër,Zhegoc,
  Abri_e_Epërme,
  Arllat,Baicë,Çikatovë_e_Re,Çikatovë_e_Vjetër,Dobroshec,Domanek,Fushticë_e_Epërme,
  Fushticë_e_Ulët,Gllabar,Gllanasellë,Gllogoc,Godanc,Gradicë,Kishnarekë,Komoran,Korroticë_e_Epërme,
  Korroticë_e_Ulët,Krajkovë,Likoshan,Llapushnik,Negroc,Nekoc,Poklek,Polluzhë,Sankoc,Shtrubullovë,
  Shtuticë,Tërdec,Tërstenik,Vasilevë,Vuçak,Zabel_i_Epërm,Zabel_i_Ulët,
  Badoc,
  Dobratin,Gushtericë_e_Epërme,Gushtericë_e_Ulët,Lepi,Livagjë,Radevë,Suhodoll,Skullan,Graçanicë,
  Çagllavicë,Llapllasellë,Preoc,Kishnicë,
  Dimcë,Dromjak,Gorancë,Han_i_Elezit,Krivenik,
  Neçavc,Paldenicë,Pustenik,Rezhancë,Seçishtë,Vërtomicë,
  Gjocaj,Jasiq,Junik,
  Bajnicë,Begracë,Biqec,
  Bob,Drenogllavë,Duraj,Elezaj,Gabricë,Gajre,Gërlicë_e_Epërme,Gjurgjedell,
  Ivajë,Kaçanik,Kaçanik_i_Vjetër,Korbliq,Kotlinë,Kovaçec,Llanishtë,Nikaj,Nikoc,Rekë,Runjevë,Semajë,
  Sllatinë,Soponicë,Stagovë,Strazhë,Vatë,
  Berivojcë,Bllatë,Boscë,Bratilloc,Busovatë,Dajkoc,Dazhnicë,
  Desivojcë,Feriqevë,Gmicë,Gogolloc,Gragjenik,Grizimë,Gjyrishec,Hajnoc,Hodonoc,Hogosht,Kamenicë,
  Karaçevë_e_Epërme,Karaçevë_e_Poshtme,Kolloleq,Kopernicë,Koretin,Kostadincë,Kranidell,Kremenatë_I,Kremenatë_II,
  Krilevë,Lajçiqi,Leshtar,Lisockë,Marocë,Meshinë,Moçar,Muçivërc,Petroc,Poliçkë,Qarrakoc,
  Rogaçicë,Ruboc,Sedllar,Strelicë,Strezoc,Svircë,Shahiq,Shipashnicë_e_Epërme,Shipashnicë_e_Poshtme,
  Tërstenë,Topanicë,Tugjec,Vaganesh,Velegllavë_e_Epërme,Velegllavë_e_Poshtme,Vriqec,Zajçec,Zhujë,
  Bërkovë,Binxhë,Bokshiq,Budisalc,Caravik,Çabiq,Deiq,Dollc,Dollovë,Dranashiq,Drsnik,
  Dugajevë,Dush,Dush_i_Vogël,Gllarevë,Grabanicë,Grabc,Gremnik,Gjurgjevik_i_Madh,Gjurgjevik_i_Vogël,
  Jagodë,Jelloc,Kërnicë,Klinafc,Klinë,Kpuz,Krushevë_e_Madhe,Krushevë_e_Vogël,Leskoc,Nagllavë,
  Përqevë,Pjetërq_i_Epërm,Pjetërq_i_Poshtëm,Qeskovë,Qupevë,Raduloc,Ranoc,Resnik,Rixhevë,Rudicë,
  Sferkë,Siqevë,Stupë,Shtupel,Ujmir,Videjë,Volljak,Zabërgjë,Zajm,Zllakuqan,
  Gërnçar,Kllokot,Mogillë,Vërboc,
  Bare,Bello_Brdë,Belluqë,Berberishtë,Bërzancë,Bistricë,Bistricë_e_Shalës,Borçan,Borovë,Cerajë,Crnotavë,
  Crven,Desetak,Dobravë,Dren,Drenovë,Dubokë,Gërkajë,Gnezhdan,Graniçan,Guli,Guvnishtë,Isevë_e_Ulët,Jarinje,
  ellakcë,Kajkovë,Kalinë,Kërnin_i_Epërm,Kërnin_i_Ulët,Kijevçiq,Koporiq,Koshuticë,Koshutovë,
  Kostin_Potok,Krushçicë,Kutnje,Leposaviq,Leshak,Llazhinë,Lloznë,Majdevë,Mekiniqe,Mihaliq,Miokovoq,
  Moshnicë,Ostraq,Pllakanicë,Pllaninicë,Postenjë_e_Ibrit,Potomilë,Pridvoricë,Qirkoviq,Rëvatskë,Rikovë,
  Rodel,Rucmanc,Seoc,Simiçishtë,Soçanicë,Trebiq,Trikosë,Tvrgjan,Ulinje,Vitanoviq,Vraqevë,Vuçë,Zabërxhjë,
  Zavratë,Zemanicë,Zërnosek,
  Akllap,Babush_i_Muhaxherve,Banullë,Breg_i_Zi,Brus,Bujan,Bukovicë,Divlakë,
  Dobrajë_e_Madhe,Dobrajë_e_Vogël,Gadime_e_Epërme,Gadime_e_Ulët,Gllanicë,Gllavicë,Grackë_e_Vjetër,
  Grackë_eVogël,Gumnasellë,Hallaç_i_Madh,Hallaç_i_Vogël,Hanroc,Janjevë,Kleqkë,Kojskë,Konjuh,Kraishtë,Krojmir,
  Leletiq,Lipjan,Llugagji,Magurë,Marec,Medvec,Mirenë,Okosnicë,Plitkoviq,Poturoc,Qellapek,Qylagë,
  Resinoc,Ribar_i_Madh,Ribar_i_Vogël,Rubofc,Rufc_i_Ri,Rufc_i_Vjetër,Sllovi,Smallushë,Shalë,Shisharkë,Teqe,Tërbufc,
  Topliqan,Torinë,Varigoc,Vërshec,Vogaçicë,Vrellë_e_Goleshit,Zllokuqan,
  Astrazup,Balincë,Banjë,Bellanicë,
  Berishë,Bubavec,Bubël,Carrallukë,Carravranë,Damanek,Dragobil,Gajrak,Garaqevë,Koshare,Jashanicë,Jellakcë,Golluboc,Guriq,Janqishtë,Joviq,
  Kërvasari,Kijevë,Lubizhdë,Lladroc,Lladroviq,Llapçevë,Llashkadrenoc,Llazicë,Marali,Maxharrë,Millanoviq,
  Mirushë,Mleqan,Ngucat,Pagarushë,Panorc,Pllaqicë,Qypevë,Rudë,Senik,Shkarashnik,Temeqinë,Tërpezë,Tërpezë_e_Poshtme,Vërmicë,
  Mamushë,
  Bajgorë,Batahir,Broboniq,Dedi,Gushac,Kaqandoll,Kçiq_i_Madh,Kçiq_i_Vogël,Koprivë,
  Koshtovë,Kovaçicë,Kutlloc,Lisicë,Lushtë,Maxherë,Mazhiq,Melenicë,Mitrovicë,Ovçar,Pirq,Rahovë,Rashan,
  Rrzhanë,Selac,Stantërg,Stranë,Suhodoll_i_Epërm,Suhodoll_i_Poshtëm,Svinjarë,Shipol,Shupkovc,
  Tunel_i_Parë,Vaganicë,Vërbnicë,Vidishiq,Vidomiriq,Vinarc_i_Epërm,Vinarc_i_Poshtëm,Vllahi,Zabërxhë,Zasellë,
  Zijaqë,Zhabar_i_Epërm,Zhabar_i_Poshtëm,
  Bolec,Bostan,Bushincë,Carevc,Dragancë,Izvor,Jasenovik,Kllobukar,
  Koretishtë,Kosaç,Kufcë_e_Epërme,Llabjan,Makresh_i_Epërm,Makresh_i_Ulët,Manishincë,Mazgovë,Miganoc,Novobërdë,
  Parallovë,Pasjak,Prekoc,Stanishor,Tërniqec,Tirincë,Zebincë,
  Babimoc,Bakshi,Breznicë,Caravodicë,Dobrosellë,
  Graboc_i_Epërm,Hade,Hamidi,Kozaricë,Leshkoshiq,Llazarevë,Mazgit,Miloshevë,Minjerë_e_Kosovës,
  Obiliq,Plemetin,Raskovë,Siboc,Shipitullë,
  Budrikë_e_Poshtme,Partesh,Pasjan,
  Bajçinë,Ballofcë,Barainë,
  Batllavë,Bellopojë,Bërvenik,Bradash,Brainë,Brecë,Buricë,Dumnicë_e_Epërme,Dumnicë_e_Poshtme,
  Dumosh,Dvorishtë,Dyz,Gërdoc,Gllamnik,Godishnjak,Halabak,Hërticë,Kaçybeg,Kalaticë,Kërpimeh,Kunushec,
  Kushevicë,Letanc,Livadicë,Lupq_i_Epërm,Lupq_i_Poshtëm,
  Lladoc,Llapashticë_e_Epërme,Llapashticë_e_Poshtme,Llaushë,Lluzhan,Majac,Merdar,Metehi,Metergoc,Miroc,Muhazob,Murgull,
  Obrançë,Orllan,Pakashticë_e_Epërme,Pakashticë_e_Poshtme,Penuhë,Peran,
  Përpellac,Podujevë,Pollatë,Popovë,Potok,Rakinicë,Reçicë,Repë,Revuq,Sallabajë,
  Sfeçël,Siboc_i_Epërm,Siboc_i_Poshtëm,Surdull,Surkish,Sylevicë,Shajkoc,
  Shakovicë,Shtedim,Tërnavë,Tërnavicë,Turuçicë,Velikarekë,Zakut,Zhiti,Kodrali,
  Ballaban,Barilevë,
  Bërnicë_e_Epërme,Bërnicë_e_Poshtme,Besi,Busi,Dabishec,Dragoc,Gllogovicë,
  Grashticë,Hajkobillë,Hajvali,Keçekollë,Koliq,Kolovicë,Kukavicë,Lebanë,Llukar,Makoc,Matiçan,
  Mramor,Nëntë_Jugoviq,Nishec,Orlloviq,Prapashticë,Prishtinë,Prugoc,Radashec,Rimanishtë,Sinidol,Sofali,Sharban,Shashkoc,Teneshdoll,Trudë,Vranidoll,Zllash,
  Atmaxhë,Billushë,Caparc,Dedaj,
  Dobrushtë,Dojnicë,Drajçiq,Dushanovë,Gornjasellë,Gorozhup,Grazhdanik,Gjonaj,
  Hoçë_e_Qytetit,Jeshkovë,Kabash,Kabash_i_Hasit,Karashëngjergj,Kobajë,Kojushë,Korishë,Krajk,
  Krushë_e_Vogël,Kushnin,Kushtendil,Landovicë,Leskovec,Lez,Lubinjë_e_Epërme,Lubinjë_e_Poshtme,
  Lubiqevë,Lubizhdë_e_Hasit,Lukinaj,Lutogllavë,Llokvicë,Malësi_e_Re,Manastiricë,Mazrek,
  Milaj,Muradem,Mushnikovë,Nashec,Nebregoshtë,Novak,Petrovë,Piranë,Pllanejë,Pllanjan,
  Poslishtë,Pouskë,Prizren,Randobravë,Reçan,Romajë,Sërbicë_e_Epërme,Sërbicë_e_Poshtme,Skorobishtë,Smaç,
  Sredskë,Struzhë,Shkozë,Shpenadi,Trepetnicë,Tupec,Velezhë,Vërbiçan,Vlashnjë,Zojz,Zhivinjan,
  Zhur,
  Bellacrkë,Bërnjak,Bratotin,Brestovc,Celinë,Çifllak,Dabidol,Dejnë,Gexhë,Hoçë_e_Madhe,Hoçë_e_Vogël,
  Kaznik,Kramovik,Krushë_e_Madhe,Mrasor,Nagavc,Nushpal,Opterushë,Pastasellë,Pataçan_i_Epërm,Pataçan_i_Ulët,
  Petkoviq,Radostë,Rahovec,Ratkoc,Reti_e_Ulët,Retijë,Sapniq,Sarosh,Senoc,Vrajakë,Zatriq,Zoçishtë,
  Berat,Kutalli,Lumas,Velabisht,Otllak,Poshnjë,Roshnik,Sinjë,Terpan,Ura_Vajgurore,Vertop,Cukalat,Kozare,
  Kuçovë,Perondi,Bogovë,Çepan,Çorovodë,Gjerbës,Skrapar,Leshnjë,Poliçan,Potom,Vendreshë,Zhepë,Bulqizë,Fushë_Bulqizë,
  Gjoricë,Trebisht,Ostren,Shupenzë,Zerqan,Martanesh,Arras,Fushë_çidhën,Kala_e_Dodës,Kastriot,Lurë,Maqellarë,Melan,
  Fushë_Muhur,Peshkopi,Qendër_Tomin,Sllovë,Zall_Dardhë,Zall_Reç,Luzni,Dibër,Mat,Baz,Derjan,Gurrë,Komsi,
  Lis,Macukull,Burrel,Rukaj,Suç,Ulëz,Xibër,Durrës,Gjepalaj,Ishëm,Katund_i_Ri,Maminas,Manëz,Rrashbull,Shijak,
  Sukth,Xhafzotaj,Bubq,Cudhi,Fushë_Krujë,Kodër_Thumanë,Krujë,Nikël,Belsh,Bradashesh,Cërrik,Elbasan,Funarë,
  Gjergjan,Gjinar,Gostimë,Gracen,Grekan,Kajan,Klos,Labinot_Fushë,Labinot_Mal,Papër,Rrasë,Shalës,Shirgjan
  ,Tregan,Zavalin,Gramsh,Kodovjat,Kushovë,Lenie,Pishaj,Poroçan,Skënderbegas,Kukur,Sult,Tunjë,Hotolisht,
  Librazhd,Lunik,Orenjë,Përrenjas,Polis,Qukës,Stëblevë,Stravaj,Rrajcë,Karinë,Pajovë,Peqin,Përparim,
  Shezë,Cakran,Dermenas,Fier,Frakull,Ruzhdie,Kuman,Kurjan,Levan,Libofshë,Mbrostar,Patos,Portëz,Roskovec,
  Strum,Topojë,Zharrës,Allkaj,Ballagat,Bubullimë,Divjakë,Dushk,Fiershegan,Grabian,Gradishtë,Hysgjokaj,
  Karbunarë,Kolonjë,Krutje,Lushnje,Rremas,Tërbuf,Mallakastër,Aranitas,Ballsh,Fratar,Greshicë,Hekal,Kutë,Ngraçan,
  Qendër,Selitë,Antigonë,Cepo,Dropull_i_Poshtëm,Dropull_i_Sipërm,Gjirokastër,Lazarat,Libohovë,Lunxhëri,
  Odrie,Picar,Pogon,Qendër_Libohovë,Zagori,Çarçovë,Frashër,Këlcyrë,Përmet,Sukë,Dishnicë,
  Petran,Buz,Fshat_Memaliaj,Krahës,Kurvelesh,Lopës,Luftinjë,Memaliaj,Qesarat,Tepelenë,Bilisht,
  Qendër_Bilisht,Miras,Hoçisht,Progër,Barmash,Çlirim,Ersekë,Mollas,Gorë,Korçë,Lekas,Libonik,Liqenas,Maliq,Mollaj,Pirg,Pojan,Vithkuq,Voskop,Voskopojë,
  Vreshtas,

  Buçimas,Çërravë,Dardhas,Pogradec,Proptisht,Trebinjë,Hudenisht,Velçan,
  Fajza,Golaj,Gjinaj,Krumë,Has,
  Arrën,Bicaj,Bushtricë,Kolsh,Kukës,Malzi,Zapod,Shishtavec,Shtiqën,Surroj,Tërthore,Topojan,Ujëmisht,Grykë_Çajë,
  Kalis,
  Bajram_Curri,Bytyç,Lekbibaj,Llugaj,Margegaj,Tropojë,
  Fushë_Kuqe,Laç,Mamurras,Milot,Kurbin,
  Balldren_i_Ri, Blinisht,Dajç,Kallmet,Kolç,Lezhë,Shëngjin,Shënkoll,Ungrej,Zejmen,Mirditë,Fan,Kaçinar,Kthjellë,
  Orosh,Rrëshen,Rubik,Malësi_e_Madhe ,
  Gruemirë,Kastrat,Kelmend,Koplik,Blerim,Fierzë,Fushë_Arrëz,
  Gjegjan,Iballë,Pukë,Qelëz,Qafë_Mali,Rrapë,Ana_e_Malit,Bërdicë,Bushat,Guri_i_Zi,Hajmel,
  Vau_i_Dejës,Postribë,Pult,Rrethinat,Shkodër,Shllak,Shosh,Velipojë,Vig_mnelë,Temal,
  Golem,Gosë,
  Helmës,Kavajë,Kryevidh,Lekaj,Luz_i_Vogel,Rrogozhinë,Sinaballaj,Synej,
  Baldushk,Bërxullë,Bërzhitë,Dajt,
  Kamëz,Kashar,Ndroq,Paskuqan,Petrelë,Pezë,Prezë,Farkë,Shëngjergj,Tiranë,Vaqarr,Vorë,Zall_Bastar,
  Zall_Herr,Kërrabë,Delvinë,Finiq,Mesopotam,Vergo,Dhivër,Konispol,Livadhja,Lukovë,Sarandë,Xarrë,
  Aliko,Markat,Ksamil,Brataj,Himarë,Kote,Novoselë,Orikum,Selenicë,Sevaster,Vllahinë,
  Vlorë,Vranisht,Armen,Devoll
  = Value
}

object AllPlaces extends Enums {
  import Countries._

  import Villages._

   val allPlaces = Map(
     Kosove ->
       Map(Pejë -> Set(Pejë, Babiq,Baran,Bellopaq,Bellopojë,Bllagajë,Bogë,Breg_i_Zi,Brestovik,Brezhanik,Broliq,Buçan,Çallapek,Dobërdol,
           Drelaj,Duboçak,Dubovë,Dugaivë,Gllaviçicë,Gllogjan,Gorazhdec,Graboc,Haxhaj,Jabllanicë,Jabllanicë_e_Madhe,
           Jabllanicë_e_Vogël,Katundi_i_Ri,Kërstoc,Kliqinë,Koshutan,Kosuriq,Kotradiq,Kryshec,Kuçishtë,Leshan,Lëvoshë,
           Lipë,Loxhë,Lubeniq,Lutogllavë,Llabjan,Llaz_Bellopaq,Llozhan,Llugaxhi,Malaj,Millovanc,Nabërgjan,Nakëll,Nepolë,
           Novosellë,Osojë,Ozdrim,Pavlan,Pepiq,Pishtan,Poçestë,Qyshk,Radavc,Ramun,Rashiq,Raushiq,Rekë_e_Allagës,Rosulë,
           Ruhot,Sigë,Stankaj,Sverkë,Shkrel,Shtupeq_i_Madh,Shtupeq_i_Vogël,Treboviq,Trestenik,Turjakë,Vitomiricë,Vragoc,
           Vranoc,Zagërmë,Zahaq,Zllapek),
       Istog->Set(Banjë,Banjicë,Belicë,Bellopojë,Carrallukë,Cerkolez,Cerrcë,Dobrushë,Dragolec,
         Drejë,Dubovë_e_Vogël,Dubravë,Gjurakoc,Istog,Istog_i_Poshtëm,Kaliqan,Kashicë,Kërninë,Kosh,Kovragë,Lubovë,
         Lubozhdë,Llugë,Llukac_i_Begut,Llukac_i_Thatë,Mojstir,Muzhevinë,Orobërdë,Osojan,Polanë,Prekallë,Prigodë,
         Rakosh,Serbobran,Sinajë,Staradran,Studenicë,Suhogërllë,Shalinovicë,Shushicë,Tomoc,Trubuhoc,Tuçep,Uçë,Veriq,
         Veriq_i_Ri,Vrellë,Zabllaq,Zallq,Zhakovë),
       Deçan-> Set(Baballoq,Beleg,Belle,Carrabreg_i_Epërm,Carrabreg_i_Ulët,
         Dashinoc,Deçan,Drenoc,Dubovik,Dubravë,Gllogjan,Gramaçel,Hulaj,Irzniq,Isniq,Kodrali,Lëbushë,
         Lumbardh,Lloqan,Llukë_e_Epërme,Llukë_e_Ulët,Maznik,Papiq,Pobërxhë,Pozhar,Prapaqan,Prekolluk,Prilep,
         Rastavicë,Ratish_i_Epërm,Ratish_i_Ulët,Sllup,Strellc_i_Epërm,Strellc_i_Ulët,Shaptej,Voksh,Vranoc_i_Vogël),
       Dragash->Set(Dragash,Baçkë,Bellobradë,Blaç,Brezne,Brod,Brodosanë,Brrut,Buçë,Buzez,Dikancë,Dragash,Glloboçicë,Kapre,Kërstec,Kosavë,
         Krushevë,Kuk,Kukjan,Kuklibeg,Leshtan,Lubovishtë,Mlikë,Orqushë,Plavë,Pllajnik,Radesh,Rapqë,Restelicë,Rrenc,
         Shajnë,Vranishtë,Xërxë,Zaplluzhë,Zgatar,Zlipotok,Zym),
       Ferizaj->Set(Ferizaj,Bablak,Babush_i_Sërbëve,Balaj,Bibaj,Burrnik,Cërnillë,
         Doganaj,Dramjak,Dubravë,Fshat_i_Vjetër,Gaçkë,Gërlicë,Greme,Jezerc,Komogllavë,Koshare,Kosinë,
         Lloshkobare,Manastircë,Mirash,Mirosalë,Muhoc,Nekodim,Nerodime_e_Epërme,Nerodime_e_Poshtme,Papaz,
         Pleshinë,Pojatë,Prelez_i_Jerlive,Prelez_i_Muhaxherve,Rahovicë,Rakaj,Sazlië,Slivovë,Softaj,Sojevë,Surqinë,
         Talinoc_i_Jerlive,Talinoc_i_Muhaxherëve,Tankosiq,Tërn,Varosh,Zaskok,Zllatar),
       Fushë_Kosovë->Set(Fushë_Kosovë,Bardh_i_Madh,Bardh_i_Vogël, Bresje,Fushë_Kosovë,Graboc_i_Poshtëm,Harilaç,Henc,Kuzmin,Lismir,Miradi_e_Epërme,Miradi_e_Poshtme,Nakaradë,
         Pomazotin,Sllatinë_e_Madhe,Sllatinë_e_Vogël,Vragoli),
       Gjakovë-> Set(Babaj_i_Bokës,Bardhaniq,Bardhasan,Batushë,Bec,Berjah,
           Bishtazhin,Bitesh,Brekoc,Brovinë,Cërmjan,Dallashaj,Damjan,Devë,Doblibarë,Dobrixhë,
           Dobrosh,Dol,Dujakë,Duzhnjë,Firajë,Firzë,Fshaj,Gërçinë,Gërgoc,Goden,Guskë,Gjakovë,Hereç,
           Jabllanicë,Jahoc,Janosh,Kodrali,Korenicë,Koshare,Kralan,Kusar,Kushavec,Lipovec,Lugbunar,
           Llugaxhi,Madanaj,Marmull,Mejë,Meqe,Moglicë,Molliq,Morinë,Nec,Nivokaz,Novosellë_e_Epërme,
           Novosellë_e_Ulët,Orize,Osek_Hylë,Osek_Pashë,Pacaj,Palabardhë,Pjetërshan,Plançor,Ponoshec,
           Popoc,Qerim,Qerret,Raçë,Radoniq,Rakoc,Rakovinë,Ramoc,Rashkoc,Rogovë,Rracaj,Rrezinë,Rrypaj,
           Skivjan,Smaq,Smolicë,Sopot,Stubëll,Sheremet,Shishman,Trakaniq,Ujz,Vogovë,Vraniq,Zylfaj,Zhabel,
           Zhdredhë,Zhub),
         Gjilan->Set(Bilincë,Bresalc,Bukovik,Burincë,Capar,Cërnicë,Çelik,Demiraj,Dobërçan,Dunav,Gadish,
           Goden,Gumnishtë,Gjilan,Haxhaj,Inatoc,Kishnapolë,Kmetoc,Kravaricë,Kurexh,Lipovicë,
           Livoç_i_Epërm,Livoç_i_Ulët,Lladovë,Llashticë,Llovcë,Malishevë,Muçibabë,Nasalë,
           Përlepnicë,Pidiq,Pograxhë,Ponesh,Selishtë,Sllakoc_i_Epërm,Sllakoc_i_Ulët,
           Sllubicë,Stançiq,Stublinë,Shillovë,Shurdhan,Terzijaj,Uglar,Velekincë,
           Vërbicë_e_Kmetocit,Vërbicë_e_Zhegocit,Vrapçiq,Zhegër,Zhegoc),
         Gllogoc->Set(Abri_e_Epërme,
           Arllat,Baicë,Çikatovë_e_Re,Çikatovë_e_Vjetër,Dobroshec,Domanek,Fushticë_e_Epërme,
           Fushticë_e_Ulët,Gllabar,Gllanasellë,Gllogoc,Godanc,Gradicë,Kishnarekë,Komoran,Korroticë_e_Epërme,
           Korroticë_e_Ulët,Krajkovë,Likoshan,Llapushnik,Negroc,Nekoc,Poklek,Polluzhë,Sankoc,Shtrubullovë,
           Shtuticë,Tërdec,Tërstenik,Vasilevë,Vërboc,Vuçak,Zabel_i_Epërm,Zabel_i_Ulët),
         Graçanicë->Set(Badoc,Batushë,Uglar,
           Dobratin,Gushtericë_e_Epërme,Gushtericë_e_Ulët,Lepi,Livagjë,Radevë,Suhodoll,Skullan,Graçanicë,
           Çagllavicë,Llapllasellë,Preoc,Shushicë,Kishnicë),
         Han_i_Elezit->Set(Dimcë,Dromjak,Gorancë,Han_i_Elezit,Krivenik,
           Neçavc,Paldenicë,Pustenik,Rezhancë,Seçishtë,Vërtomicë),
         Junik -> Set(Gjocaj,Jasiq,Junik),
         Kaçanik->Set(Bajnicë,Begracë,Biqec,
           Bob,Doganaj,Drenogllavë,Dubravë,Duraj,Elezaj,Gabricë,Gajre,Gërlicë_e_Epërme,Glloboçicë,Gjurgjedell,
           Ivajë,Kaçanik,Kaçanik_i_Vjetër,Korbliq,Kotlinë,Kovaçec,Llanishtë,Nikaj,Nikoc,Rekë,Runjevë,Semajë,
           Sllatinë,Soponicë,Stagovë,Strazhë,Vatë),
         Kamenicë -> Set(Berivojcë,Bllatë,Boscë,Bratilloc,Busovatë,Dajkoc,Dazhnicë,
           Desivojcë,Feriqevë,Gmicë,Gogolloc,Gragjenik,Grizimë,Gjyrishec,Hajnoc,Hodonoc,Hogosht,Kamenicë,
           Karaçevë_e_Epërme,Karaçevë_e_Poshtme,Kolloleq,Kopernicë,Koretin,Kostadincë,Kranidell,Kremenatë_I,Kremenatë_II,
           Krilevë,Lajçiqi,Leshtar,Lisockë,Marocë,Meshinë,Moçar,Muçivërc,Novosellë,Petroc,Poliçkë,Qarrakoc,Rahovicë,
           Rogaçicë,Ruboc,Sedllar,Strelicë,Strezoc,Svircë,Shahiq,Shipashnicë_e_Epërme,Shipashnicë_e_Poshtme,
           Tërstenë,Topanicë,Tugjec,Vaganesh,Velegllavë_e_Epërme,Velegllavë_e_Poshtme,Vriqec,Zajçec,Zhujë),
         Klinë -> Set(Bërkovë,Binxhë,Bokshiq,Budisalc,Caravik,Çabiq,Deiq,Dobërdol,Dollc,Dollovë,Dranashiq,Drenoc,Drsnik,
           Dugajevë,Dush,Dush_i_Vogël,Gllarevë,Grabanicë,Grabc,Gremnik,Gjurgjevik_i_Madh,Gjurgjevik_i_Vogël,
           Jagodë,Jashanicë,Jelloc,Kërnicë,Klinafc,Klinë,Kpuz,Krushevë_e_Madhe,Krushevë_e_Vogël,Leskoc,Nagllavë,
           Përqevë,Pjetërq_i_Epërm,Pjetërq_i_Poshtëm,Pograxhë,Qeskovë,Qupevë,Raduloc,Ranoc,Resnik,Rixhevë,Rudicë,
           Sferkë,Siqevë,Stupë,Shtupel,Ujmir,Videjë,Volljak,Zabërgjë,Zajm,Zllakuqan),
         Leposaviq -> Set(Gërnçar,Kllokot,Mogillë,Vërboc,
           Bare,Bello_Brdë,Belluqë,Berberishtë,Bërzancë,Bistricë,Bistricë_e_Shalës,Borçan,Borovë,Cerajë,Crnotavë,
           Crven,Desetak,Dobravë,Dren,Drenovë,Dubokë,Gërkajë,Gnezhdan,Graniçan,Guli,Guvnishtë,Isevë_e_Ulët,Jarinje,
              Jashanicë,Jellakcë,Kajkovë,Kalinë,Kërnin_i_Epërm,Kërnin_i_Ulët,Kijevçiq,Koporiq,Koshuticë,Koshutovë,
           Kostin_Potok,Krushçicë,Krushevë,Kutnje,Leposaviq,Leshak,Llazhinë,Lloznë,Majdevë,Mekiniqe,Mihaliq,Miokovoq,
           Moshnicë,Ostraq,Pllakanicë,Pllaninicë,Popoc,Postenjë_e_Ibrit,Potomilë,Pridvoricë,Qirkoviq,Rëvatskë,Rikovë,
           Rodel,Rucmanc,Seoc,Simiçishtë,Sllatinë,Soçanicë,Trebiq,Trikosë,Tvrgjan,Ulinje,Vitanoviq,Vraqevë,Vuçë,Zabërxhjë,
           Zavratë,Zemanicë,Zërnosek),
         Lipjan->Set(Akllap,Babush_i_Muhaxherve,Baicë,Banullë,Breg_i_Zi,Brus,Bujan,Bukovicë,Divlakë,
           Dobrajë_e_Madhe,Dobrajë_e_Vogël,Gadime_e_Epërme,Gadime_e_Ulët,Gllanicë,Gllavicë,Gllogoc,Grackë_e_Vjetër,
           Grackë_eVogël,Gumnasellë,Hallaç_i_Madh,Hallaç_i_Vogël,Hanroc,Janjevë,Kleqkë,Kojskë,Konjuh,Kraishtë,Krojmir,
           Leletiq,Lipjan,Lipovicë,Llugagji,Llugë,Magurë,Marec,Medvec,Mirenë,Okosnicë,Plitkoviq,Poturoc,Qellapek,Qylagë,
           Resinoc,Ribar_i_Madh,Ribar_i_Vogël,Rubofc,Rufc_i_Ri,Rufc_i_Vjetër,Sllovi,Smallushë,Shalë,Shisharkë,Teqe,Tërbufc,
           Topliqan,Torinë,Varigoc,Vërshec,Vogaçicë,Vrellë,Vrellë_e_Goleshit,Zllokuqan),
         Malishevë->Set(Astrazup,Balincë,Banjë,Bellanicë,
           Berishë,Bubavec,Bubël,Carrallukë,Carravranë,Damanek,Dragobil,Gajrak,Garaqevë,Golluboc,Guriq,Janqishtë,Joviq,
           Kërvasari,Kijevë,Lubizhdë,Lladroc,Lladroviq,Llapçevë,Llashkadrenoc,Llazicë,Malishevë,Marali,Maxharrë,Millanoviq,
           Mirushë,Mleqan,Ngucat,Pagarushë,Panorc,Pllaqicë,Qypevë,Rudë,Senik,Shkarashnik,Temeqinë,Tërpezë,Tërpezë_e_Poshtme,
           Turjakë,Vërmicë),
         Mamushë->Set(Mamushë),
         Mitrovicë->Set(Bajgorë,Bare,Batahir,Broboniq,Dedi,Gushac,Kaqandoll,Kçiq_i_Madh,Kçiq_i_Vogël,Koprivë,
           Koshtovë,Kovaçicë,Kutlloc,Lisicë,Lushtë,Maxherë,Mazhiq,Melenicë,Mitrovicë,Ovçar,Pirq,Rahovë,Rashan,
           Rekë,Rrzhanë,Selac,Stantërg,Stranë,Suhodoll_i_Epërm,Suhodoll_i_Poshtëm,Svinjarë,Shipol,Shupkovc,Tërstenë,
           Tunel_i_Parë,Vaganicë,Vërbnicë,Vidishiq,Vidomiriq,Vinarc_i_Epërm,Vinarc_i_Poshtëm,Vllahi,Zabërxhë,Zasellë,
           Zijaqë,Zhabar_i_Epërm,Zhabar_i_Poshtëm),
         Novobërdë->Set(Bolec,Bostan,Bushincë,Carevc,Dragancë,Izvor,Jasenovik,Kllobukar,
           Koretishtë,Kosaç,Kufcë_e_Epërme,Llabjan,Makresh_i_Epërm,Makresh_i_Ulët,Manishincë,Mazgovë,Miganoc,Novobërdë,
           Parallovë,Pasjak,Prekoc,Stanishor,Strazhë,Tërniqec,Tirincë,Zebincë),
         Obiliq->Set(Babimoc,Bakshi,Breznicë,Caravodicë,Dobrosellë,
           Graboc_i_Epërm,Hade,Hamidi,Kozaricë,Kryshec,Leshkoshiq,Llazarevë,Mazgit,Miloshevë,Minjerë_e_Kosovës,
           Obiliq,Plemetin,Raskovë,Siboc,Shipitullë),
         Partesh -> Set(Budrikë_e_Poshtme,Partesh, Pasjan),
         Podujevë -> Set(Bajçinë,Ballofcë,Barainë,
           Batllavë,Bellopojë,Bërvenik,Bllatë,Bradash,Brainë,Brecë,Buricë,Dobërdol,Dobratin,Dumnicë_e_Epërme,Dumnicë_e_Poshtme,
           Dumosh,Dvorishtë,Dyz,Gërdoc,Gllamnik,Godishnjak,Halabak,Hërticë,Kaçybeg,Kalaticë,Kërpimeh,Kunushec,
           Kushevicë,Letanc,Livadicë,Lupq_i_Epërm,Lupq_i_Poshtëm,
           Lladoc,Llapashticë_e_Epërme,Llapashticë_e_Poshtme,Llaushë,
           Llugë,Lluzhan,Majac,Merdar,Metehi,Metergoc,Miroc,Muhazob,Murgull,
           Obrançë,Orllan,Pakashticë_e_Epërme,Pakashticë_e_Poshtme,Penuhë,Peran,
           Përpellac,Podujevë,Pollatë,Popovë,Potok,Rakinicë,Reçicë,Repë,Revuq,Sallabajë,
           Sfeçël,Siboc_i_Epërm,Siboc_i_Poshtëm,Sllatinë,Surdull,Surkish,Sylevicë,Shajkoc,
           Shakovicë,Shtedim,Tërnavë,Tërnavicë,Turuçicë,Velikarekë,Zakut,Zhiti),
         Prishtinë -> Set(Prishtinë,Ballaban,Barilevë,
           Bërnicë_e_Epërme,Bërnicë_e_Poshtme,Besi,Busi,Çagllavicë,Dabishec,Dragoc,Drenoc,Gllogovicë,
           Grashticë,Hajkobillë,Hajvali,Keçekollë,Koliq,Kolovicë,Kukavicë,Lebanë,Llukar,Makoc,Marec,Matiçan,
           Mramor,Nëntë_Jugoviq,Nishec,Orlloviq,Prapashticë,Prugoc,Radashec,Rimanishtë,Sinidol,Siqevë,
           Slivovë,Sofali,Sharban,Shashkoc,Teneshdoll,Trudë,Vranidoll,Zllash,Zllatar),
         Prizren -> Set(Atmaxhë,Billushë,Caparc,Dedaj,
           Dobrushtë,Dojnicë,Drajçiq,Dushanovë,Gërnçar,Gornjasellë,Gorozhup,Grazhdanik,Gjonaj,
           Hoçë_e_Qytetit,Jabllanicë,Jeshkovë,Kabash,Kabash_i_Hasit,Karashëngjergj,Kobajë,Kojushë,Korishë,Krajk,
           Krushë_e_Vogël,Kushnin,Kushtendil,Landovicë,Leskovec,Lez,Lubinjë_e_Epërme,Lubinjë_e_Poshtme,
           Lubiqevë,Lubizhdë,Lubizhdë_e_Hasit,Lukinaj,Lutogllavë,Llokvicë,Malësi_e_Re,Manastiricë,Mazrek,
           Medvec,Milaj,Muradem,Mushnikovë,Nashec,Nebregoshtë,Novak,Novosellë,Petrovë,Piranë,Pllanejë,Pllanjan,
           Poslishtë,Pouskë,Prizren,Randobravë,Reçan,Romajë,Sërbicë_e_Epërme,Sërbicë_e_Poshtme,Skorobishtë,Smaç,
           Sredskë,Struzhë,Shkozë,Shpenadi,Trepetnicë,Tupec,Velezhë,Vërbiçan,Vërmicë,Vlashnjë,Zojz,Zym,Zhivinjan,
           Zhur),
         Rahovec->Set(Bellacrkë,Bërnjak,Bratotin,Brestovc,Celinë,Çifllak,Dabidol,Dejnë,Drenoc,Gexhë,Hoçë_e_Madhe,Hoçë_e_Vogël,
           Kaznik,Kramovik,Krushë_e_Madhe,Mrasor,Nagavc,Nushpal,Opterushë,Pastasellë,Pataçan_i_Epërm,Pataçan_i_Ulët,
           Petkoviq,Polluzhë,Radostë,Rahovec,Ratkoc,Reti_e_Ulët,Retijë,Sapniq,Sarosh,Senoc,Vrajakë,Xërxë,Zatriq,Zoçishtë)
       ),


     Albania -> Map(
       Berat -> Set(Berat,Kutalli,Lumas,Velabisht,Otllak,Poshnjë,Roshnik,Sinjë,Terpan,Ura_Vajgurore,Vertop,Cukalat),
       Kuçovë -> Set(Kozare, Kuçovë,Perondi),
       Skrapar -> Set(Bogovë,Çepan,Çorovodë,Gjerbës,Skrapar,Leshnjë,Poliçan,Potom,Vendreshë,Zhepë),
       Bulqizë -> Set(Bulqizë,Fushë_Bulqizë, Gjoricë,Trebisht,Ostren,Shupenzë,Zerqan,Martanesh),
       Dibër -> Set(Dibër,Arras,Fushë_çidhën,Kala_e_Dodës,Kastriot,Lurë,Maqellarë,Melan,Fushë_Muhur,Peshkopi,Qendër_Tomin,Sllovë,Zall_Dardhë,Zall_Reç,Luzni),
       Mat -> Set(Mat, Baz,Derjan,Gurrë,Komsi, Lis,Macukull,Burrel,Rukaj,Suç,Ulëz,Xibër),
       Durrës -> Set(Durrës,Gjepalaj,Ishëm,Katund_i_Ri,Maminas,Manëz,Rrashbull,Shijak, Sukth,Xhafzotaj),
       Krujë -> Set(Krujë,Bubq,Cudhi,Fushë_Krujë,Kodër_Thumanë,Nikël),
       Elbasan -> Set(Belsh,Bradashesh,Cërrik,Elbasan,Funarë,
         Gjergjan,Gjinar,Gostimë,Gracen,Grekan,Kajan,Klos,Labinot_Fushë,Labinot_Mal,Papër,Rrasë,Shalës,Shirgjan
         ,Tregan,Zavalin),
       Librazhd -> Set(Hotolisht, Librazhd,Lunik,Orenjë,Përrenjas,Polis,Qukës,Stëblevë,Stravaj,Rrajcë),
       Peqin -> Set(Gjocaj,Karinë,Pajovë,Peqin,Përparim, Shezë),
       Fier -> Set(Cakran,Dermenas,Fier,Frakull,Ruzhdie,Kuman,Kurjan,Levan,Libofshë,Mbrostar,Patos,Portëz,Roskovec,
         Strum,Topojë,Zharrës),
       Lushnje -> Set(Allkaj,Ballagat,Bubullimë,Divjakë,Dushk,Fiershegan,Grabian,Gradishtë,Hysgjokaj,
         Karbunarë,Krutje,Lushnje,Rremas,Tërbuf),
       Mallakastër ->Set(Aranitas,Ballsh,Fratar,Greshicë,Hekal,Kutë,Ngraçan,
         Mallakastër,Selitë),
       Gjirokastër -> Set(Antigonë,Cepo,Dropull_i_Poshtëm,Dropull_i_Sipërm,Gjirokastër,Lazarat,Libohovë,Lunxhëri,
         Odrie,Picar,Pogon,Qendër_Libohovë,Zagori),
       Përmet -> Set(Përmet,Ballaban,Çarçovë,Frashër,Këlcyrë,Sukë,Dishnicë, Petran ),
       Tepelenë -> Set(Buz,Fshat_Memaliaj,Krahës,Kurvelesh,Lopës,Luftinjë,Memaliaj,Qesarat,Tepelenë),
       Devoll -> Set(Devoll,Bilisht,Miras,Qendër_Bilisht,Hoçisht,Progër),
       Kolonjë -> Set(Barmash,Çlirim,Ersekë,Mollas, Novosellë, Kolonjë),
       Korçë -> Set(Drenovë,Gorë,Korçë,Lekas,Libonik,Liqenas,Maliq,Mollaj,Pirg,Pojan,Vithkuq,Voskop,Voskopojë,
         Vreshtas),
       Pogradec -> Set(Buçimas,Çërravë,Dardhas,Pogradec,Proptisht,Trebinjë,Hudenisht,Velçan),
       Has -> Set(Fajza,Golaj, Gjinaj,Krumë, Has),
       Kukës -> Set(Arrën,Bicaj,Bushtricë,Kolsh,Kukës,Malzi,Zapod,Shishtavec,Shtiqën,Surroj,Tërthore,Topojan,Ujëmisht,Grykë_Çajë,
         Kalis),
       Tropojë->Set(Bajram_Curri,Bytyç,Lekbibaj,Llugaj,Margegaj,Tropojë),
       Kurbin -> Set(Kurbin,Fushë_Kuqe,Laç,Mamurras,Milot),
       Lezhë -> Set(Balldren_i_Ri, Blinisht,Dajç,Kallmet,Kolç,Lezhë,Shëngjin,Shënkoll,Ungrej,Zejmen),
       Mirditë -> Set(Mirditë,Fan,Kaçinar,Kthjellë,
         Orosh,Rrëshen,Rubik,Selitë),
       Malësi_e_Madhe -> Set(Malësi_e_Madhe ,
         Gruemirë,Kastrat,Kelmend,Koplik),
       Pukë -> Set(Blerim,Fierzë,Fushë_Arrëz,
         Gjegjan,Iballë,Pukë,Qelëz,Qafë_Mali,Rrapë),
       Shkodër-> Set(Ana_e_Malit,Bërdicë,Bushat,Guri_i_Zi,Hajmel,
         Vau_i_Dejës,Postribë,Pult,Rrethinat,Shkodër,Shllak,Shosh,Velipojë,Vig_mnelë,Temal),
       Kavajë->Set(Golem,Gosë,
         Helmës,Kavajë,Kryevidh,Lekaj,Luz_i_Vogel,Rrogozhinë,Sinaballaj,Synej),
       Tiranë-> Set(Baldushk,Bërxullë,Bërzhitë,Dajt,
         Kamëz,Kashar,Ndroq,Paskuqan,Petrelë,Pezë,Prezë,Farkë,Shëngjergj,Tiranë,Vaqarr,Vorë,Zall_Bastar,
         Zall_Herr,Kërrabë),
       Delvinë->Set(Delvinë,Vergo,Dhivër,Konispol,Livadhja,Lukovë,Sarandë,Xarrë,
         Aliko,Markat,Ksamil),
       Vlorë -> Set(Brataj,Himarë,Kote,Novoselë,Orikum,Selenicë,Sevaster,Shushicë,Vllahinë,
         Vlorë,Vranisht,Armen)))
}

