export const RoomTags: string[] = [
  $localize`Room Ensuite bathroom`,
  $localize`Wake up service`,
  $localize`Dining table`,
  $localize`Toilet paper`,
];

export const PropertyTags: string[] = [
  $localize`Property Ensuite bathroom`,
  $localize`Wake up service`,
  $localize`Dining table`,
  $localize`Toilet paper`,
];

export const RoomDescriptions: string[] = [
  $localize`Budget Single Room`,
  $localize`Deluxe Single Room`,
  $localize`Deluxe Single Room with Balcony`,
  $localize`Deluxe Single Room with Sea View`,
  $localize`Economy Single Room`,
  $localize`Large Single Room`,
  $localize`New Year's Eve Special - Single Room`,
  $localize`Single Room`,
  $localize`Single Room - Disability Access`,
  $localize`Single Room with Balcony`,
  $localize`Single Room with Bath`,
  $localize`Single Room with Bathroom`,
  $localize`Single Room with Garden View`,
  $localize`Single Room with Lake View`,
  $localize`Single Room with Mountain View`,
  $localize`Single Room with Park View`,
  $localize`Single Room with Pool View`,
  $localize`Single Room with Private Bathroom`,
  $localize`Single Room with Private External Bathroom`,
  $localize`Single Room with Sea View`,
  $localize`Single Room with Shared Bathroom`,
  $localize`Single Room with Shared Shower and Toilet`,
  $localize`Single Room with Shared Toilet`,
  $localize`Single Room with Shower`,
  $localize`Single Room with Terrace`,
  $localize`Small Single Room`,
  $localize`Standard Single Room`,
  $localize`Standard Single Room with Mountain View`,
  $localize`Standard Single Room with Sauna`,
  $localize`Standard Single Room with Sea View`,
  $localize`Standard Single Room with Shared Bathroom`,
  $localize`Standard Single Room with Shower`,
  $localize`Superior Single Room`,
  $localize`Superior Single Room with Lake View`,
  $localize`Superior Single Room with Sea View`,
  $localize`Budget Double Room`,
  $localize`Business Double Room with Gym Access`,
  $localize`Deluxe Double Room`,
  $localize`Deluxe Double Room (1 adult + 1 child)`,
  $localize`Deluxe Double Room (1 adult + 2 children)`,
  $localize`Deluxe Double Room (2 Adults + 1 Child)`,
  $localize`Deluxe Double Room with Balcony`,
  $localize`Deluxe Double Room with Balcony and Sea View`,
  $localize`Deluxe Double Room with Bath`,
  $localize`Deluxe Double Room with Castle View`,
  $localize`Deluxe Double Room with Extra Bed`,
  $localize`Deluxe Double Room with Sea View`,
  $localize`Deluxe Double Room with Shower`,
  $localize`Deluxe Double Room with Side Sea View`,
  $localize`Deluxe Double or Twin Room`,
  $localize`Deluxe King Room`,
  $localize`Deluxe Queen Room`,
  $localize`Deluxe Room`,
  $localize`Deluxe Room (1 adult + 1 child)`,
  $localize`Deluxe Room (1 adult + 2 children)`,
  $localize`Deluxe Room (2 Adults + 1 Child)`,
  $localize`Double Room`,
  $localize`Double Room (1 Adult + 1 Child)`,
  $localize`Double Room - Disability Access`,
  $localize`Double Room with Balcony`,
  $localize`Double Room with Balcony (2 Adults + 1 Child)`,
  $localize`Double Room with Balcony (3 Adults)`,
  $localize`Double Room with Balcony and Sea View`,
  $localize`Double Room with Extra Bed`,
  $localize`Double Room with Garden View`,
  $localize`Double Room with Lake View`,
  $localize`Double Room with Mountain View`,
  $localize`Double Room with Patio`,
  $localize`Double Room with Pool View`,
  $localize`Double Room with Private Bathroom`,
  $localize`Double Room with Private External Bathroom`,
  $localize`Double Room with Sea View`,
  $localize`Double Room with Shared Bathroom`,
  $localize`Double Room with Shared Toilet`,
  $localize`Double Room with Spa Bath`,
  $localize`Double Room with Terrace`,
  $localize`Economy Double Room`,
  $localize`King Room`,
  $localize`King Room - Disability Access`,
  $localize`King Room with Balcony`,
  $localize`King Room with Garden View`,
  $localize`King Room with Lake View`,
  $localize`King Room with Mountain View`,
  $localize`King Room with Pool View`,
  $localize`King Room with Roll-In Shower - Disability Access`,
  $localize`King Room with Sea View`,
  $localize`King Room with Spa Bath`,
  $localize`Large Double Room`,
  $localize`Queen Room`,
  $localize`Queen Room - Disability Access`,
  $localize`Queen Room with Balcony`,
  $localize`Queen Room with Garden View`,
  $localize`Queen Room with Pool View`,
  $localize`Queen Room with Sea View`,
  $localize`Queen Room with Shared Bathroom`,
  $localize`Queen Room with Spa Bath`,
  $localize`Small Double Room`,
  $localize`Standard Double Room`,
  $localize`Standard Double Room with Fan`,
  $localize`Standard Double Room with Shared Bathroom`,
  $localize`Standard King Room`,
  $localize`Standard Queen Room`,
  $localize`Superior Double Room`,
  $localize`Superior King Room`,
  $localize`Superior Queen Room`,
  $localize`Budget Twin Room`,
  $localize`Deluxe Double Room with Two Double Beds`,
  $localize`Deluxe Queen Room with Two Queen Beds`,
  $localize`Deluxe Twin Room`,
  $localize`Deluxe Twin Room with Sea View`,
  $localize`Double Room with Two Double Beds`,
  $localize`Economy Twin Room`,
  $localize`King Room with Two King Beds`,
  $localize`Large Twin Room`,
  $localize`Queen Room with Two Queen Beds`,
  $localize`Queen Room with Two Queen Beds - Disability Access`,
  $localize`Small Twin Room`,
  $localize`Standard Double Room with Two Double Beds`,
  $localize`Standard Queen Room with Two Queen Beds`,
  $localize`Standard Twin Room`,
  $localize`Standard Twin Room with Garden View`,
  $localize`Standard Twin Room with Mountain View`,
  $localize`Standard Twin Room with Sea View`,
  $localize`Standard Twin Room with Shared Bathroom`,
  $localize`Standard Twin Room with Sofa`,
  $localize`Superior Double Room with Two Double Beds`,
  $localize`Superior King or Twin Room`,
  $localize`Superior Queen Room with Two Queen Beds`,
  $localize`Superior Twin Room`,
  $localize`Superior Twin Room with City View`,
  $localize`Superior Twin Room with Garden View`,
  $localize`Superior Twin Room with Sauna`,
  $localize`Superior Twin Room with Sea View`,
  $localize`Twin Room`,
  $localize`Twin Room - Disability Access`,
  $localize`Twin Room with Balcony`,
  $localize`Twin Room with Bath`,
  $localize`Twin Room with Bathroom`,
  $localize`Twin Room with City View`,
  $localize`Twin Room with Extra Bed`,
  $localize`Twin Room with Garden View`,
  $localize`Twin Room with Lake View`,
  $localize`Twin Room with Mountain View`,
  $localize`Twin Room with Pool View`,
  $localize`Twin Room with Private Bathroom`,
  $localize`Twin Room with Private External Bathroom`,
  $localize`Twin Room with Sea View`,
  $localize`Twin Room with Shared Bathroom`,
  $localize`Twin Room with Shared Toilet`,
  $localize`Twin Room with Shower`,
  $localize`Twin Room with Terrace`,
  $localize`Twin Room with View`,
  $localize`Basic Triple Room`,
  $localize`Basic Triple Room with Shared Bathroom`,
  $localize`Budget Triple Room`,
  $localize`Classic Triple Room`,
  $localize`Comfort Triple Room`,
  $localize`Comfort Triple Room with Shower`,
  $localize`Deluxe Triple Room`,
  $localize`Deluxe Triple Room with Sea View`,
  $localize`Economy Triple Room`,
  $localize`Economy Triple Room with Shared Bathroom`,
  $localize`Executive Triple Room`,
  $localize`Luxury Triple Room`,
  $localize`Standard Triple Room`,
  $localize`Standard Triple Room with Sea View`,
  $localize`Superior Triple Room`,
  $localize`Superior Triple Room with Sea View`,
  $localize`Triple Room`,
  $localize`Triple Room - Disability Access`,
  $localize`Triple Room with Balcony`,
  $localize`Triple Room with Bath`,
  $localize`Triple Room with Bathroom`,
  $localize`Triple Room with City View`,
  $localize`Triple Room with Garden View`,
  $localize`Triple Room with Lake View`,
  $localize`Triple Room with Mountain View`,
  $localize`Triple Room with Pool View`,
  $localize`Triple Room with Private Bathroom`,
  $localize`Triple Room with Private External Bathroom`,
  $localize`Triple Room with Sea View`,
  $localize`Triple Room with Shared Bathroom`,
  $localize`Triple Room with Shared Toilet`,
  $localize`Triple Room with Shower`,
  $localize`Triple Room with Terrace`,
  $localize`Triple Room with View`,
  $localize`Classic Quadruple Room`,
  $localize`Comfort Quadruple Room`,
  $localize`Deluxe Quadruple Room`,
  $localize`Deluxe Queen Room with Two Queen Beds`,
  $localize`Duplex Quadruple Room`,
  $localize`Economy Quadruple Room`,
  $localize`Economy Quadruple Room with Shared Bathroom`,
  $localize`Executive Queen Room with Two Queen Beds`,
  $localize`Japanese-Style Quadruple Room`,
  $localize`King Room with Two King Beds`,
  $localize`Luxury Quadruple Room`,
  $localize`Premium Quadruple Room`,
  $localize`Quadruple Room`,
  $localize`Quadruple Room - Disability Access`,
  $localize`Quadruple Room with Balcony`,
  $localize`Quadruple Room with Bath`,
  $localize`Quadruple Room with Bathroom`,
  $localize`Quadruple Room with Garden View`,
  $localize`Quadruple Room with Lake View`,
  $localize`Quadruple Room with Mountain View`,
  $localize`Quadruple Room with Private Bathroom`,
  $localize`Quadruple Room with Private External Bathroom`,
  $localize`Quadruple Room with Sea View`,
  $localize`Quadruple Room with Shared Bathroom`,
  $localize`Quadruple Room with Shower`,
  $localize`Quadruple Room with Terrace`,
  $localize`Queen Room with Two Queen Beds`,
  $localize`Queen Room with Two Queen Beds - Disability Access`,
  $localize`Standard Quadruple Room`,
  $localize`Standard Queen Room with Two Queen Beds`,
  $localize`Superior Quadruple Room`,
  $localize`Superior Queen Room with Two Queen Beds`,
  $localize`Deluxe Family Room`,
  $localize`Deluxe Family Suite`,
  $localize`Family Bungalow`,
  $localize`Family Cabin on Boat`,
  $localize`Family Double Room`,
  $localize`Family Junior Suite`,
  $localize`Family Room`,
  $localize`Family Room - Disability Access`,
  $localize`Family Room with Balcony`,
  $localize`Family Room with Bath`,
  $localize`Family Room with Bathroom`,
  $localize`Family Room with Garden View`,
  $localize`Family Room with Lake View`,
  $localize`Family Room with Mountain View`,
  $localize`Family Room with Private Bathroom`,
  $localize`Family Room with Sauna`,
  $localize`Family Room with Sea View`,
  $localize`Family Room with Shared Bathroom`,
  $localize`Family Room with Shower`,
  $localize`Family Room with Side Sea View`,
  $localize`Family Room with Terrace`,
  $localize`Family Studio`,
  $localize`Family Suite`,
  $localize`Family Suite with Balcony`,
  $localize`Japanese-Style Room`,
  $localize`Standard Family Room`,
  $localize`Superior Family Room`,
  $localize`Deluxe Double Studio`,
  $localize`Deluxe Junior Suite`,
  $localize`Deluxe King Studio`,
  $localize`Deluxe King Suite`,
  $localize`Deluxe Queen Studio`,
  $localize`Deluxe Queen Suite`,
  $localize`Deluxe Studio`,
  $localize`Deluxe Suite`,
  $localize`Deluxe Suite with Sea View`,
  $localize`Deluxe Suite with Spa Bath`,
  $localize`Duplex Suite`,
  $localize`Executive Suite`,
  $localize`Family Studio`,
  $localize`Family Suite`,
  $localize`Junior Suite`,
  $localize`Junior Suite with Balcony`,
  $localize`Junior Suite with Canal View`,
  $localize`Junior Suite with Garden View`,
  $localize`Junior Suite with Mountain View`,
  $localize`Junior Suite with Ocean View`,
  $localize`Junior Suite with Pool View`,
  $localize`Junior Suite with Private Pool`,
  $localize`Junior Suite with Sauna`,
  $localize`Junior Suite with Sea View`,
  $localize`Junior Suite with Terrace`,
  $localize`King Studio`,
  $localize`King Studio with Sofa Bed`,
  $localize`King Suite`,
  $localize`King Suite with Balcony`,
  $localize`King Suite with Ocean View`,
  $localize`King Suite with Pool View`,
  $localize`King Suite with Sea View`,
  $localize`King Suite with Spa Bath`,
  $localize`One-Bedroom Suite`,
  $localize`Presidential Suite`,
  $localize`Queen Studio`,
  $localize`Queen Studio - Disability Access`,
  $localize`Queen Suite`,
  $localize`Queen Suite with Pool View`,
  $localize`Queen Suite with Sea View`,
  $localize`Queen Suite with Spa Bath`,
  $localize`Standard Double Suite`,
  $localize`Standard Studio`,
  $localize`Standard Suite`,
  $localize`Standard Triple Studio`,
  $localize`Studio`,
  $localize`Studio - Disability Access`,
  $localize`Studio with Balcony`,
  $localize`Studio with Garden View`,
  $localize`Studio with Ocean View`,
  $localize`Studio with Pool View`,
  $localize`Studio with Sea View`,
  $localize`Studio with Sofa Bed`,
  $localize`Studio with Spa Bath`,
  $localize`Studio with Terrace`,
  $localize`Suite`,
  $localize`Suite with Balcony`,
  $localize`Suite with City View`,
  $localize`Suite with Garden View`,
  $localize`Suite with Hot Tub`,
  $localize`Suite with Lake View`,
  $localize`Suite with Mountain View`,
  $localize`Suite with Pool View`,
  $localize`Suite with Private Pool`,
  $localize`Suite with River View`,
  $localize`Suite with Sauna`,
  $localize`Suite with Sea View`,
  $localize`Suite with Spa Access`,
  $localize`Suite with Spa Bath`,
  $localize`Suite with Terrace`,
  $localize`Superior King Suite`,
  $localize`Superior Studio`,
  $localize`Superior Suite`,
  $localize`Superior Suite with Sea View`,
  $localize`Three-Bedroom Suite`,
  $localize`Two-Bedroom Suite`,
  $localize`Deluxe Double Studio`,
  $localize`Deluxe King Studio`,
  $localize`Deluxe Queen Studio`,
  $localize`Deluxe Studio`,
  $localize`Duplex Studio`,
  $localize`Family Studio`,
  $localize`King Studio`,
  $localize`King Studio with Sofa Bed`,
  $localize`Queen Studio`,
  $localize`Queen Studio - Disability Access`,
  $localize`Standard Studio`,
  $localize`Standard Triple Studio`,
  $localize`Studio`,
  $localize`Studio - Disability Access`,
  $localize`Studio - Split Level`,
  $localize`Studio with Balcony`,
  $localize`Studio with Garden View`,
  $localize`Studio with Lake View`,
  $localize`Studio with Mountain View`,
  $localize`Studio with Ocean View`,
  $localize`Studio with Pool View`,
  $localize`Studio with Sea View`,
  $localize`Studio with Sofa Bed`,
  $localize`Studio with Spa Bath`,
  $localize`Studio with Terrace`,
  $localize`Superior Studio`,
  $localize`Apartment`,
  $localize`Apartment - Ground Floor`,
  $localize`Apartment - Split Level`,
  $localize`Apartment With Shared Bathroom`,
  $localize`Apartment with Balcony`,
  $localize`Apartment with Garden View`,
  $localize`Apartment with Lake View`,
  $localize`Apartment with Mountain View`,
  $localize`Apartment with Pool View`,
  $localize`Apartment with Sauna`,
  $localize`Apartment with Sea View`,
  $localize`Apartment with Shower`,
  $localize`Apartment with Terrace`,
  $localize`Deluxe Apartment`,
  $localize`Duplex Apartment`,
  $localize`Loft`,
  $localize`Maisonette`,
  $localize`One-Bedroom Apartment`,
  $localize`Penthouse Apartment`,
  $localize`Standard Apartment`,
  $localize`Studio Apartment`,
  $localize`Studio Apartment with Sea View`,
  $localize`Superior Apartment`,
  $localize`Superior Apartment with Sauna`,
  $localize`Three-Bedroom Apartment`,
  $localize`Two-Bedroom Apartment`,
];
